apiVersion: apps/v1
kind: Deployment
metadata:
  name: ReservationManagement
  labels:
    app: ReservationManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReservationManagement
  template:
    metadata:
      labels:
        app: ReservationManagement
    spec:
      containers:
        - name: ReservationManagement
          image: username/ReservationManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5